class AppStrings {
  static const login = "Login";
  static const String email = "Email";
  static const String EnterYourEmail = "Enter Your Email";
  static const String password = "Password";
  static const String EnterYourPassword = "Enter Your Password";
  static const String RememberMe = "Remember me";
  static const String ForgetPass = "Forget Password ?";
  static const String NotValidEmail = "The email is not valid";
  static const String youMustEnterYourEmail = "you must enter your email";
  static const String youMustEnterYourPassword = "you must enter your Password";
  static const String NotValidPassword = "The Password is not valid";
  static const String Continue = "Continue ";
  static const String emailVerification = "Email verification";
  static const String ResetPassword = "Reset Password";
  static const String NewPassword = "New Password";
  static const String ConfirmPassword = "Confirm Password";
  static const String passwordDoesntMatch = "Password Doesn't Match";
  static const String passwordSuccessfulyChanged = "Password Successfuly Changed";
  static const String dontHaveAnAccount = "Don't have an account ?";
  static const String signUp = "Sign Up";
  static const String explore = "Explore";
  static const String result = "Result";
  static const String profile = "Profile";
  static const String languages = "Languages";
  static const String instructions = "Instructions";
  static const String instructionContent = "Lorem ipsum dolor sit amet consectetur.";
  static const String startExam = "Start Exam";
}