class AppStrings {
  static const login = "Login";
  static const String email = "Email";
  static const String EnterYourEmail = "Enter Your Email";
  static const String password = "Password";
  static const String EnterYourPassword = "Enter Your Password";
  static const String RememberMe = "Remember me";
  static const String ForgetPass = "Forget Password ?";
  static const String NotValidEmail = "The email is not valid";
  static const String youMustEnterYourEmail = "you must enter your email";
  static const String youMustEnterYourPassword = "you must enter your Password";
  static const String NotValidPassword = "The Password is not valid";
  static const String Continue = "Continue ";
  static const String emailVerification = "Email verification";
  static const String ResetPassword = "Reset Password";
  static const String NewPassword = "New Password";
  static const String ConfirmPassword = "Confirm Password";
  static const String passwordDoesntMatch = "Password Doesn't Match";
  static const String passwordSuccessfulyChanged =
      "Password Successfuly Changed";
  static const String dontHaveAnAccount = "Don't have an account ?";
  static const String signUp = "Sign Up";
  static const String explore = "Explore";
  static const String result = "Result";
  static const String profile = "Profile";
  static const String veiwScore = "View score";
  static const String timeOut = "Time out !!";
  static const String question = "Question";
  static const String retry = "Retry";
  static const String error = "Somthing Went Wrong";
  static const String back = "Back";
  static const String finish = "Finish";
  static const String next = "Next";
  static const String examScore = "Exam Score";
  static const String yourScore = 'Your Score';
  static const String correct = 'Correct';
  static const String incorrect = 'Incorrect';
  static const String showResults = 'Show results';
  static const String startAgain = 'Start again';  static const String survey = "Survey";
  static const String search = "Search";
  static String signup = "Signup";
  static String enterYourUserName = "Enter your user name";
  static String username = "User name";
  static String firstName = "First name";
  static String enterYourFirstName = "Enter your first name";
  static String lastName = "Last name";
  static String enterYourLastName = "Enter your last name";
  static String phoneNumber = "Phone number";
  static String enterYourPhoneNumber = "Enter your phone number";
  static String confirmPassword = "Confirm password";
  static String passwordNotMatched = "Password not matched";
  static String notValidUserName = "This user name is not valid";
  static String signupAppBarTitle = "Sign Up";
  static String alreadyHaveAnAccount = "Already have an account?";
  static const String languages = "Languages";
  static const String instructions = "Instructions";
  static const String instructionContent = "Lorem ipsum dolor sit amet consectetur.";
  static const String startExam = "Start Exam";
  static const String tokin = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZmZjMGM3OGZiMTlhZDk1NWIyNDRlNSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYzNjQ2MjExfQ.lZ1fx-1kkqfuTf-RZTA7TCSFVB9ZZaB7O9jxt8HBeIg";


}
